# Generated by Django 5.2.9 on 2026-01-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], default='FULL_DAY', max_length=20)),
            ],
        ),
    ]
